spring.data.mongodb.uri=mongodb://localhost:27017/cloudshare


server.servlet.context-path=/api/v1.0

spring.data.mongodb.auto-index-creation=false

spring.autoconfigure.exclude = org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

clerk.issuer=https://grateful-sunbeam-78.clerk.accounts.dev
clerk.jwks-url=https://grateful-sunbeam-78.clerk.accounts.dev/.well-known/jwks.json
clerk.webhook.secret=WUBadcdhfdjFOqc1/sqmT4boFaJfBUnR

#file upload configuration

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=25MB

razorpay.key.id=your_key_id
razorpay.key.secret=your_key_secret

